# Grammar for lower case letters
<string> ::= <letter>|<letter><string>
<letter> ::= <vowel>|<consonant>|<space>
<space> ::= <space>
# Vowels and consonats
<vowel> ::= <vowel>
<consonant> ::= <consonant>